### ISSUE TITLE
[FEAT] 선택들을 입력받는 페이지 생성

### ISSUE THREAD

**Issue by commitcomplete** [commitcomplete/Destiny#2]
### 문제 상황
- 사용자의 선택에 따라 선택지를 입력 받는 페이지 생성

### 해결 방안
- 하단부의 버튼을 통해 사용자에게 선택지를 동적으로 생성
 
### TODO
- [ ] 입력 페이지 구성
- [ ] 입력 칸 구성
- [ ] 버튼 동작에 따라 동적으로 입력 칸 추가
- [ ] 사용자가 추가를 마치고 나면 다음 페이지로 이동할 수 있게끔 버튼 추가
- [ ] 네비게이션 연결

### 비고 및 한계
*해당 이슈에서 해결하지 못한 사항들*
- 최소 2개의 선택지는 받게 하고 넘기기
