### ISSUE TITLE
[FEAT] 애니메이션 픽 페이지 생성

### ISSUE THREAD

**Issue by commitcomplete** [commitcomplete/Destiny#3]
### 문제 상황
- 애니메이션을 선택 할 수 있는 페이지 생성
- 별표 표시를 통해 기본 값으로 사용할 애니메이션 선택
### 해결 방안
- UserDefaults 를 이용해서 기본 값 저장
- 화면 3분할 후 애니메이션 썸네일 3개 생성
 
### TODO
- [ ] 애니메이션 픽 페이지 생성
- [ ] 타이틀 제외한 화면 3분할 박스 생성
- [ ] 애니메이션 선택 및 썸네일 생성
- [ ] 네비게이션 연결

### 비고 및 한계
*해당 이슈에서 해결하지 못한 사항들*
- 다수의 선택지에서도 사용자에게 과정을 잘 보여줄 수 있는 애니메이션 3개 선별
