### ISSUE TITLE
[FEAT] 랜덤 결과 페이지 생성

### ISSUE THREAD

**Issue by commitcomplete** [commitcomplete/Destiny#5]
### 문제 상황
- 랜덤 결과 페이지 생성
- 이전 애니메이션 페이지에서 선택받은 선택지 표시
- 선택받지 못한 선택지도 표시
- 공유하기
- 다시하기
- 메인페이지로 돌아가기

### 해결 방안
- Environment Object 를 통해 선택지 공유받기
- 애플이 기본으로 제공하는 공유하기 사용
- 다시하기를 통해 애니메이션 페이지로 이동
- 메인페이지로 돌아가기를 통해 restart
 
### TODO
- [ ] 선택지를 공유할 Environment Object 생성
- [ ] 공유하기 버튼 추가
- [ ] 다시하기 버튼 추가
- [ ] 메인 페이지 돌아가기 버튼 명명 + 추가

### 비고 및 한계
*해당 이슈에서 해결하지 못한 사항들*
- 다시하기와 메인페이지로 돌아가기의 구분
- 다시하기를 했을 때 애니메이션을 다시 보여주는게 주는지의 여부
- 다시하기를 했을 때 이동한 페이지가 애니메이션을 선택하는 부분으로 돌아갈지에 대한 여부
- 선택 받지 못한 선택지와 선택 받은 선택지의 배치
